metadata:
  name: breakpoint_ подкаст
  description: |
    Разговоры о программой инженерии и информационных технологиях.
    Смотрим в суть вещей, и не стесняемся делиться своим мнением.
  authors: Руслан (@rkiyanchuk), Игорь (@ikalnitskyi), Роман (@rpodoliaka)
  url: https://breakpoint-podcast.github.io

pipes:
  compile:
    - name: import-processors
      args:
        imports:
          - custom/get-episodes-from-github = episodes:process
          - custom/set-welcome-episode = welcome:process
        from_: "%(here)s/processors"

    - name: custom/get-episodes-from-github
      args:
        repository: breakpoint-podcast/episodes
        enclosure: breakpoint-{tag_name}.mp3

    - name: commonmark

    - name: chain
      args:
        order_by: published_at
        direction: desc

    - name: custom/set-welcome-episode

    - name: feed
      args:
        syndication_format: rss
        feed:
          title:
            $ref: 'metadata:#/name'
          link:
            href:
              $ref: 'metadata:#/url'
          description:
            $ref: 'metadata:#/description'
          language: uk
          itunes_author:
            $ref: metadata:#/authors
          itunes_subtitle:
            $ref: 'metadata:#/description'
          itunes_category:
            - cat: Technology
              sub: Software How-To
            - cat: Technology
              sub: Tech News
          itunes_owner:
            name:
              $ref: metadata:#/authors
            email: breakpoint_@xsnippet.org
          itunes_image: https://breakpoint-podcast.github.io/static/itunes.png
          itunes_explicit: "no"
        item:
          id:
            $ref: item:#/url
          title:
            $ref: item:#/name
          content:
            $ref: item:#/content
          link:
            href:
              $ref: item:#/absurl
            rel: alternate
          enclosure:
            url:
              $ref: item:#/enclosure_url
            type:
              $ref: item:#/enclosure_type
            length:
              $ref: item:#/enclosure_size
          published:
            $ref: item:#/published_at
          itunes_duration:
            $ref: item:#/duration
      when:
        - item.source.match("episode://*")

    - name: jinja2
      args:
        template: episode.j2
        themes: ["%(here)s/theme"]
      when:
        - item.source.match("episode://*") or item.source.match("welcome://")

    - name: source
      args:
        path: favicon/

    - name: save
      args:
        to: _site
